### ISSUE TITLE
Persistent MemoryError on Workshop notebook 07_train/05_Convert_BERT step 2

### ISSUE THREAD

**Issue by barneym** [data-science-on-aws/workshop#30]
Received a MemoryError and was unable to resolve through any of the techniques raised in the class, including:
1) Verifying no other notebooks running
2) Verifying only one endpoint active (for the failing job)
3) Clearing and rerunning the notebook
4) Clearing and rerunning the entire 07 series
5) Running code step-by-step manually
6) Relogging to the console
7) Verifying no other process activity within the AWS account

Using burner account with t3.medium instance in east (Oregon) region.

Error message received:
`
ERROR: Exception:
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 216, in _main
    status = self.run(options, args)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 325, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 340, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 469, in prepare_linked_requirement
    hashes=self._get_linked_req_hashes(req)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 259, in unpack_url
    hashes=hashes,
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 130, in get_http_url
    link, downloader, temp_dir.path, hashes
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 278, in _download_http_url
    download = downloader(link)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pip/_internal/network/download.py", line 170, in __call__
    resp = _http_get_download(self._session, link)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pip/_internal/network/download.py", line 139, in _http_get_download
    resp = session.get(target_url, headers=HEADERS, stream=True)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pip/_internal/network/session.py", line 421, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pip/_vendor/cachecontrol/adapter.py", line 44, in send
    cached_response = self.controller.cached_request(request)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pip/_vendor/cachecontrol/controller.py", line 145, in cached_request
    resp = self.serializer.loads(request, cache_data)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pip/_vendor/cachecontrol/serialize.py", line 97, in loads
    return getattr(self, "_loads_v{}".format(ver))(request, data)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pip/_vendor/cachecontrol/serialize.py", line 184, in _loads_v4
    cached = msgpack.loads(data, raw=False)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pip/_vendor/msgpack/fallback.py", line 129, in unpackb
    ret = unpacker._unpack()
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pip/_vendor/msgpack/fallback.py", line 670, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pip/_vendor/msgpack/fallback.py", line 670, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pip/_vendor/msgpack/fallback.py", line 683, in _unpack
    return bytes(obj)
MemoryError
`

**Comment by cfregly** [comment]
Thanks for the report.  We are looking into this.  The short/term fix is to use a notebook instance with >= 8GB RAM.  The instance we used today was 4GB RAM.

We will keep an eye on this as we prefer to use the smaller 4GB notebook instances to reduce costs.
